name: custom actions
on:
    push:
        branches: [workflow]

jobs:
    testing-actions:
        runs-on: ubuntu-latest
        steps:
            - name: checkout files to vm
              uses: actions/checkout@v2.3.4

            - name: Custom action 1 greeting
              uses: ./.github/actions/hello/
              id: hello
              with:
                  who-to-greet: "World"

            - run: |
                  echo "Time: ${{steps.hello.outputs.time}}"
